# Generated by Django 5.0.6 on 2024-05-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=19)),
                ('order_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('discount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=19)),
                ('result_price', models.PositiveIntegerField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='hello.carmodel')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='hello.cartype')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='hello.carmodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='hello.parttype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('whole_price', models.PositiveIntegerField()),
                ('ordering_time', models.DateTimeField()),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hello.client')),
                ('master', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hello.master')),
                ('part', models.ManyToManyField(to='hello.part')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hello.promocode')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='hello.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hello.servicetype'),
        ),
        migrations.AddField(
            model_name='master',
            name='specialization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='hello.specialization'),
        ),
    ]
