# Generated by Django 5.0.6 on 2024-05-22 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='hello.specialization'),
        ),
        migrations.AlterField(
            model_name='part',
            name='car_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='hello.carmodel'),
        ),
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='hello.parttype'),
        ),
    ]
