# Generated by Django 5.0.6 on 2024-05-22 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_master_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='specialization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='hello.specialization'),
        ),
    ]
