# Generated by Django 5.0.6 on 2024-05-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_master_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promocode',
        ),
    ]
