# Generated by Django 5.0.6 on 2024-05-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='part',
        ),
    ]
