# Generated by Django 5.0.6 on 2024-05-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_remove_order_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.client')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.master')),
            ],
        ),
    ]
