# Generated by Django 5.0.6 on 2024-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='img_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
