# Generated by Django 5.0.6 on 2024-05-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_master_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
