# Generated by Django 5.0.6 on 2024-05-24 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 24, 18, 50, 18, 747859)),
        ),
    ]
