# Generated by Django 5.0.6 on 2024-05-24 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_qa_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
