# Generated by Django 5.0.6 on 2024-06-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_alter_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCredentials',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hello.client')),
                ('login', models.CharField(default='login', max_length=20)),
                ('password', models.CharField(default='password', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCredentials',
            fields=[
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hello.master')),
                ('login', models.CharField(default='login', max_length=20)),
                ('password', models.CharField(default='password', max_length=20)),
            ],
        ),
    ]
