# Generated by Django 5.0.6 on 2024-06-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_alter_client_age_alter_master_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
