# Generated by Django 5.2.1 on 2025-06-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='master',
            name='img_url',
        ),
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters_photos/'),
        ),
    ]
