# Generated by Django 5.2.1 on 2025-10-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0025_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.TextField(blank=True, default='СВИДЕТЕЛЬСТВО\n\nо предоставлении услуг автосервиса\n\nг. [Город]\n"[Дата]"\n\nНастоящим удостоверяется, что\n\nАвтосервис "[Название компании]"\n(ИНН [номер], ОГРН [номер])\n\nвнесен в реестр сервисных организаций и имеет право оказывать услуги по:\n\nтехническому обслуживанию автомобилей,\n\nдиагностике и ремонту,\n\nгарантийному и постгарантийному обслуживанию.\n\nРегистрационный номер: [XXXX]\n\nПодпись руководителя _____________\nМ.П.'),
        ),
    ]
